Repository sealsystems/node-request-service, pull requests merged in 2023-05, with the labels that each got.

#506 Update build configuration
  package-lock.json
Labels: automatic-merge

#507 Update build configuration
  package-lock.json
Labels: automatic-merge

#508 Update build configuration
  packaging/linux/rpm/build.sh
  packaging/linux/rpm/resource/start_no_envconsul.sh
  packaging/windows/msi/build.ps1
  packaging/windows/msi/resource/run_no_envconsul.bat
Labels: automatic-merge

#509 Update build configuration
  package-lock.json
Labels: automatic-merge

#510 Update build configuration
  package-lock.json
Labels: automatic-merge

#511 Update build configuration
  package-lock.json
Labels: automatic-merge

#512 Update build configuration
  package-lock.json
Labels: automatic-merge

#513 Update build configuration
  package-lock.json
Labels: automatic-merge

#514 Update build configuration
  package-lock.json
Labels: automatic-merge

#515 Update build configuration
  package-lock.json
Labels: automatic-merge

#516 Update build configuration
  package-lock.json
Labels: automatic-merge

#517 Update build configuration
  package-lock.json
Labels: automatic-merge

#519 Update build configuration
  package-lock.json
Labels: automatic-merge

#518 feat: Added option for reading JSON response
  README.md
  lib/requestService.js
  lib/response.js
  package-lock.json
  package.json
  test/requestServiceTest.js
Labels: release/minor, release/feat

#520 chore: Moved build config back to oss module
  .github/workflows/publish-on-npmjs-org.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update-build-config.yml
  .npmignore
  .vscode/launch.json
  LICENSE
  README.md
  package-lock.json
  package.json
Labels: release/patch, release/chore

#521 Update build configuration
  package-lock.json
Labels: automatic-merge

#522 Update build configuration
  package-lock.json
Labels: automatic-merge

#523 Update build configuration
  package-lock.json
Labels: automatic-merge

#524 Update build configuration
  package-lock.json
Labels: automatic-merge

#525 Update build configuration
  package-lock.json
Labels: automatic-merge

#526 Update build configuration
  package-lock.json
Labels: automatic-merge

#527 Update build configuration
  package-lock.json
Labels: automatic-merge

#528 Update build configuration
  package-lock.json
Labels: automatic-merge

#529 Update build configuration
  package-lock.json
Labels: automatic-merge

#530 Update build configuration
  package-lock.json
Labels: automatic-merge

#531 Update build configuration
  package-lock.json
Labels: automatic-merge

#532 Update build configuration
  package-lock.json
Labels: automatic-merge

#533 Update build configuration
  package-lock.json
Labels: automatic-merge

#534 Update build configuration
  package-lock.json
Labels: automatic-merge
