Repository sealsystems/node-request-service, pull requests merged in 2023-11, with the labels that each got.

#598 Update build configuration
  .github/workflows/publish-on-npmjs-org.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update-build-config.yml
  .nvmrc
  package-lock.json
Labels: automatic-merge

#599 chore: update connect-service
  package-lock.json
  package.json
Labels: release/patch, release/chore

#600 fix: Update sealsystems dependencies (patch only)
  package-lock.json
  package.json
Labels: release/patch, release/fix, automatic-merge
