Repository sealsystems/node-request-service, pull requests merged in 2024-03, with the labels that each got.

#602 fix: yo
  .github/workflows/update-build-config.yml
Labels: release/patch, release/fix

#603 Update build configuration
  .github/workflows/publish-on-npmjs-org.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update-build-config.yml
  .nvmrc
  LICENSE
  package-lock.json
  packaging/windows/msi/build.patch-images.ps1
Labels: automatic-merge

#604 chore: Update package.json
  package.json
Labels: release/patch, release/chore

#605 feat: Update sealsystems dependencies (patch/minor only)
  package-lock.json
  package.json
Labels: release/minor, release/feat, automatic-merge

#606 Update build configuration
  .github/workflows/publish-on-npmjs-org.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update-build-config.yml
  .nvmrc
  package-lock.json
Labels: automatic-merge
